name: Build Windows Installer

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name pmpt --console --clean --noconfirm main.py

    - name: Create icon file
      run: |
        pip install Pillow
        python create-icon.py

    - name: Setup Inno Setup
      run: |
        choco install innosetup -y
        
    - name: Build installer with Inno Setup
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Test executable
      run: |
        .\dist\pmpt.exe version

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: pmpt-windows-exe
        path: dist/pmpt.exe

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: pmpt-windows-installer
        path: dist/installer/pmpt-setup.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/pmpt.exe
          dist/installer/pmpt-setup.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}